# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='author',
        ),
    ]
