# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_review_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
