# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_review_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_url',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
