# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181217_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_url',
        ),
    ]
