# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='review-user-image/'),
            preserve_default=False,
        ),
    ]
