# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181220_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course-image/'),
            preserve_default=False,
        ),
    ]
