# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
