# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_course_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location_title', models.TextField()),
                ('location_code', models.TextField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=250, null=True)),
                ('event_url', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
