# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
