# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
