# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 05:26
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190107_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('category_name',), unique=True, verbose_name='slug'),
        ),
    ]
