# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190110_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
