# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 04:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_course_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
